services:
  naver-map-app:
    build: .
    container_name: map-service-container
    ports:
      - "8080:8080"
    restart: always
    depends_on:
      - redis
  
  redis:
    image: redis:latest
    container_name: map-redis
    ports:
      - "6379:6379"
    restart: always