naver:
  url:
    search:
      local: https://openapi.naver.com/v1/search/local.json
      image: https://openapi.naver.com/v1/search/image
  client:
    # id: rbOcu3Ycb9k8JFpBFMCZ
    id: ${NAVER_CLIENT_ID}
    # secret: wMwFgik8Fl
    secret: ${NAVER_CLIENT_SECRET}

server:
  port: 9090